[package]
authors = ["The Lyken developers"]
description = "Experimental reactive component system."
license = "MIT/Apache-2.0"
name = "lyken"
repository = "https://github.com/lykenware/lyken"
version = "0.1.0"

[[bin]]
name = "lex-dart"

[[bin]]
name = "test-dsl"

[dependencies]
difference = "1.0.0"
unicode-xid = "0.1.0"
walkdir = "1.0.7"
