[package]
authors = ["The Lyken developers"]
description = "Experimental reactive component system."
license = "MIT/Apache-2.0"
name = "lyken"
repository = "https://github.com/lykenware/lyken"
version = "0.1.0"
[[bin]]
name = "test-dart-lex"
[[bin]]
name = "test-dart-parse"
[[bin]]
name = "test-dsl"

[dependencies]
difference = "1.0.0"
enum_primitive = "0.1.1"
error-chain = "0.10.0"
unicode-width = "0.1.4"
unicode-xid = "0.1.0"
walkdir = "1.0.7"
