[package]
authors = ["The Lyken developers"]
description = "GLL parser generator."
license = "MIT/Apache-2.0"
name = "lyken-gll"
repository = "https://github.com/lykenware/lyken"
version = "0.1.0"

[dependencies]
indexing = "0.3.1"
ordermap = "0.3.0"

[lib]
doctest = false
test = false
